# name: Vercel Preview Deployment
# env:
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
# on:
#   pull_request:
#   push:
#     branches-ignore:
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: amondnet/vercel-action@v25 #deploy
#         with:
#           vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
#           github-token: ${{ secrets.G_TOKEN }} #Optional 
#           vercel-args: '--prod' #Optional
#           vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
#           vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
#           working-directory: ./react-app

      # - name: Install Vercel CLI
      #   run: npm install --global vercel@latest
      # - name: Pull Vercel Environment Information
      #   run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Build Project Artifacts
      #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Deploy Project Artifacts to Vercel
      #   run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

# name: Deploy on Vercel

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Deploy to Vercel
#       uses: amondnet/vercel-deploy-action@v20
#       with:
#         vercel-token: ${{ secrets.VERCEL_TOKEN }}
#         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
#         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
#